### ISSUE TITLE
Webpage content is loaded 'insecurely'

### ISSUE THREAD

**Issue by rkokkelk** [qistoph/WiFiQR#1]
Hi,

The webpage contains many references to scripts and other content which are loaded using HTTP. Because the initial page on github.io is loaded over HTTPS the other scripts are not automatically loaded.

Verified on Firefox and Chromium, opening the WifiQR webpage will result in 'Not secure' warning and errors and will result in some scripts not being loaded automatically. Verified that most scripts can easily be loaded using HTTPS.

**Comment by qistoph** [comment]
Thanks!
Made some changes, to load the resources using the same protocol as the page was loaded with and a fix for the Twitter platform.js loading where you changed one http to https too many.
